# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('geom', djgeojson.fields.PolygonField()),
            ],
        ),
    ]
