# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_map_mapelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='slug',
            field=models.SlugField(default='hhh', editable=False),
            preserve_default=False,
        ),
    ]
