# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170428_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapelement',
            name='data',
            field=models.IntegerField(),
        ),
    ]
