# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='country',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='core.Country'),
            preserve_default=False,
        ),
    ]
