# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_polygon_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='polygon',
            old_name='country',
            new_name='region',
        ),
    ]
