# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170429_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='base_color',
            field=models.CharField(default='FFEDA0', max_length=6),
        ),
        migrations.AddField(
            model_name='map',
            name='grades',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
