# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:00
from __future__ import unicode_literals

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170501_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='base_color',
        ),
        migrations.AddField(
            model_name='map',
            name='end_color',
            field=core.models.ColorField(default='ffeda0', max_length=6),
        ),
        migrations.AddField(
            model_name='map',
            name='start_color',
            field=core.models.ColorField(default='bd0026', max_length=6),
        ),
    ]
