# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170506_0535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
