# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 04:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='date_of_information',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 7, 4, 42, 44, 307715), help_text='An year or date when the information was measured.'),
        ),
    ]
