# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170507_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='date_of_information',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 7, 6, 3, 30, 765830, tzinfo=utc), help_text='An year or date when the information was measured.'),
        ),
    ]
