# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 08:54
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170507_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='geom',
            field=djgeojson.fields.MultiPolygonField(),
        ),
    ]
