# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20170507_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='maps', to='core.Category'),
        ),
    ]
