# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170507_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='logarithmic_scale',
            field=models.BooleanField(default=False, help_text='If True - logarithmic scale will be used.'),
        ),
    ]
