# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_map_logarithmic_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('columnrange', 'Column range'), ('bar-stacked', 'Stacked bar'), ('column-stacked', 'Stacked column'), ('bar-negative-stack', 'Bar with negative stack')], max_length=32)),
                ('maps', models.ManyToManyField(related_name='charts', to='core.Map')),
            ],
        ),
    ]
