# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='user',
            field=models.ForeignKey(default=1, help_text='Map owner.', on_delete=django.db.models.deletion.CASCADE, related_name='charts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
