# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_chart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='slug',
            field=models.SlugField(default='', editable=False, help_text='The slug that will be user for urls.'),
            preserve_default=False,
        ),
    ]
