# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_chart_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='type',
        ),
    ]
