# Generated by Django 3.0.5 on 2020-04-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20170525_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='grades',
            field=models.PositiveSmallIntegerField(default=8, help_text='How many grades you would like to have', verbose_name='grades'),
        ),
        migrations.AlterField(
            model_name='mapelement',
            name='polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_elements', to='core.Polygon'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
