# Generated by Django 3.0.6 on 2020-05-10 13:55

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_migrate_social_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=256)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(help_text='Plot owner.',
                                           on_delete=django.db.models.deletion.CASCADE,
                                           related_name='plots',
                                           to=settings.AUTH_USER_MODEL,
                                           verbose_name='user')),
            ],
        ),
    ]
