# Generated by Django 5.1.6 on 2025-02-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_plot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
