# Generated by Django 3.0.6 on 2020-05-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20200408_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
